#!/bin/sh

# Install Menu Extra

open /Library/Application\ Support/HWMonitor/MenuCracker.menu
sleep 3 
open /Library/Application\ Support/HWMonitor/HWMonitorExtra.menu
sleep 3
killall SystemUIServer

exit 0